apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: yash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "myDatabase"
   #     volumeMounts:
   #    - name: mytest-volume
   #       mountPath: /data/db
   #   volumes:
   #   - name: mytest-volume
   #     persistentVolumeClaim:
   #       claimName: my-ebc-pvc
